repoURL: 'https://github.com/pjkfckr/GitOps_k8s.git'
apps:
  - name: demo
    project: default
    namespace: default
    source:
      path: demo
      customValues: true
      values:
        - values-eks.yaml
#  - name: prometheus
#    project: default
#    namespace: prom
#    source:
#      path: prometheus
#      customValues: true
#      values:
#        - values-eks.yaml
#  - name: grafana
#    project: default
#    namespace: grafana
#    source:
#      path: grafana
#      customValues: true
#      values:
#        - values-eks.yaml