installCRD: true

controller:
  replicas: 1

repoServer:
  replicas: 1

server:
  replicas: 1
  service:
    type: NodePort
    namedTargetPort: false
  ingress:
    enabled: false
  extraArgs:
    - --insecure
  config:
    url: http://127.0.0.1:30080

    repositories: |
      - url: 'https://github.com/pjkfckr/GitOps_k8s.git'

    accounts.admin: apiKey, login

    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: c509e7c366a63729d7ff
            clientSecret: 30098e178e6cd44b370d19ea3ff62cd40fd48689
            orgs:
            - name: park-single-organization

  rbacConfig:
    policy.default: role:readonly
    policy.csv: | 
      p, role:org-devops, applications, *, */*, allow
      p, role:org-devops, clusters, *, *, allow
      p, role:org-devops, repositories, *, *, allow
      g, park-single-organization:devops, role:org-devops

redis:
  enabled: true

redis-ha:
  enabled: false